[package]
name = "wormhole-contract"
edition.workspace = true
license.workspace = true
repository.workspace = true
version = "0.0.1"

[features]
default = []
std = []
export-abi = ["stylus-sdk/export-abi"]

[dependencies]
stylus-sdk.workspace = true
alloy-primitives.workspace = true
alloy-sol-types.workspace = true
mini-alloc.workspace = true
keccak-const.workspace = true
libsecp256k1 = { workspace = true }
sha3 = "0.10.8"
base64 = "0.21"

[dev-dependencies]
motsu.workspace = true

[lib]
crate-type = ["lib", "cdylib"]
