[package]
name = "wormhole-contract"
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[features]
default = []
std = []

[dependencies]
stylus-sdk.workspace = true
alloy-primitives.workspace = true
alloy-sol-types.workspace = true
mini-alloc.workspace = true
keccak-const.workspace = true
secp256k1 = { version = "0.31.0", features = ["rand", "recovery"] }
sha3 = "0.10.8"

[dev-dependencies]
motsu.workspace = true

[lib]
crate-type = ["lib", "cdylib"]
