[profile.default]
solc_version = '0.8.29'
evm_version = "paris"
optimizer = true
optimizer_runs = 200
src = 'contracts'
# Tests are in the forge-test directory
test = 'forge-test'

libs = ['lib', 'node_modules']

# This doesn't work on ../../../node_modules alone because the sources from
# parent directories are also represented as absolute paths and won't doesn't
# match the relative paths in the source files. Therefore, we are adding
# the absolute path for the node_modules directory in the github CI to
# make sure that the CI runs successfully.
ignored_warnings_from = [
    "lib",
    "node_modules/",
    "/home/runner/work/pyth-crosschain/pyth-crosschain/node_modules",
]

[rpc_endpoints]
rpc_url="${RPC_URL}"
local = "http://localhost:8545"

[etherscan]
etherscan_api_key = { key = "${ETHERSCAN_API_KEY}" }
