[workspace]
members = [
    "contracts/wormhole",
]
resolver = "2"

[workspace.package]
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/pyth-network/pyth-crosschain"
version = "0.1.0"

[workspace.dependencies]
stylus-sdk = { version = "0.6.0", default-features = false }
alloy-primitives = { version = "0.7.6", default-features = false, features = ["tiny-keccak"] }
alloy-sol-types = { version = "0.7.6", default-features = false }
mini-alloc = "0.4.2"
motsu = "0.1.0"
keccak-const = "0.2.0"
k256 = { version = "0.13.3", default-features = false, features = ["ecdsa"] }
libsecp256k1 = { version = "0.7.1", default-features = false, features = ["static-context", "hmac"] }

[profile.dev]
panic = "abort"

[profile.release]
opt-level = "z"           # Optimize for size instead of speed
lto = true               # Link-time optimization
strip = true             # Strip debug symbols
panic = "abort"          # Smaller panic handling
codegen-units = 1        # Better optimization (slower build, smaller binary)
