[workspace]
members = [
    "contracts/wormhole",
    "contracts/pyth",
    "contracts/sample",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/pyth-network/pyth-crosschain"
version = "0.1.0"

[workspace.dependencies]
stylus-sdk = { version = "0.6.0", default-features = false }
alloy-primitives = { version = "0.7.6", default-features = false, features = ["tiny-keccak"] }
alloy-sol-types = { version = "0.7.6", default-features = false }
mini-alloc = "0.4.2"
motsu = "0.1.0"
keccak-const = "0.2.0"
k256 = { version = "0.13.3", default-features = false, features = ["ecdsa"] }
libsecp256k1 = { version = "0.7.1", default-features = false, features = ["static-context"] }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
